//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.16 at 02:41:04 PM CEST 
//


package org.openehealth.ipf.gazelle.validation.core.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openehealth.ipf.gazelle.validation.core.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HL7V2XConformanceProfileUseCasePostCondition_QNAME = new QName("", "PostCondition");
    private final static QName _HL7V2XConformanceProfileUseCasePreCondition_QNAME = new QName("", "PreCondition");
    private final static QName _HL7V2XConformanceProfileUseCaseDerivedEvent_QNAME = new QName("", "DerivedEvent");
    private final static QName _HL7V2XConformanceProfileUseCaseEventFlow_QNAME = new QName("", "EventFlow");
    private final static QName _HL7V2XConformanceProfileUseCaseActor_QNAME = new QName("", "Actor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openehealth.ipf.gazelle.validation.core.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HL7V2XStaticDef }
     * 
     */
    public HL7V2XStaticDef createHL7V2XStaticDef() {
        return new HL7V2XStaticDef();
    }

    /**
     * Create an instance of {@link HL7V2XConformanceProfile }
     * 
     */
    public HL7V2XConformanceProfile createHL7V2XConformanceProfile() {
        return new HL7V2XConformanceProfile();
    }

    /**
     * Create an instance of {@link SegmentType }
     * 
     */
    public SegmentType createSegmentType() {
        return new SegmentType();
    }

    /**
     * Create an instance of {@link SegmentType.Field }
     * 
     */
    public SegmentType.Field createSegmentTypeField() {
        return new SegmentType.Field();
    }

    /**
     * Create an instance of {@link SegmentType.Field.Component }
     * 
     */
    public SegmentType.Field.Component createSegmentTypeFieldComponent() {
        return new SegmentType.Field.Component();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link HL7V2XStaticDef.SegGroup }
     * 
     */
    public HL7V2XStaticDef.SegGroup createHL7V2XStaticDefSegGroup() {
        return new HL7V2XStaticDef.SegGroup();
    }

    /**
     * Create an instance of {@link HL7V2XConformanceProfile.UseCase }
     * 
     */
    public HL7V2XConformanceProfile.UseCase createHL7V2XConformanceProfileUseCase() {
        return new HL7V2XConformanceProfile.UseCase();
    }

    /**
     * Create an instance of {@link HL7V2XConformanceProfile.Encodings }
     * 
     */
    public HL7V2XConformanceProfile.Encodings createHL7V2XConformanceProfileEncodings() {
        return new HL7V2XConformanceProfile.Encodings();
    }

    /**
     * Create an instance of {@link HL7V2XConformanceProfile.DynamicDef }
     * 
     */
    public HL7V2XConformanceProfile.DynamicDef createHL7V2XConformanceProfileDynamicDef() {
        return new HL7V2XConformanceProfile.DynamicDef();
    }

    /**
     * Create an instance of {@link HL7V2XConformanceProfile.HL7V2XStaticDefRef }
     * 
     */
    public HL7V2XConformanceProfile.HL7V2XStaticDefRef createHL7V2XConformanceProfileHL7V2XStaticDefRef() {
        return new HL7V2XConformanceProfile.HL7V2XStaticDefRef();
    }

    /**
     * Create an instance of {@link UseCaseElementType }
     * 
     */
    public UseCaseElementType createUseCaseElementType() {
        return new UseCaseElementType();
    }

    /**
     * Create an instance of {@link SegmentType.Field.DataValues }
     * 
     */
    public SegmentType.Field.DataValues createSegmentTypeFieldDataValues() {
        return new SegmentType.Field.DataValues();
    }

    /**
     * Create an instance of {@link SegmentType.Field.Component.SubComponent }
     * 
     */
    public SegmentType.Field.Component.SubComponent createSegmentTypeFieldComponentSubComponent() {
        return new SegmentType.Field.Component.SubComponent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseCaseElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PostCondition", scope = HL7V2XConformanceProfile.UseCase.class)
    public JAXBElement<UseCaseElementType> createHL7V2XConformanceProfileUseCasePostCondition(UseCaseElementType value) {
        return new JAXBElement<UseCaseElementType>(_HL7V2XConformanceProfileUseCasePostCondition_QNAME, UseCaseElementType.class, HL7V2XConformanceProfile.UseCase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseCaseElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PreCondition", scope = HL7V2XConformanceProfile.UseCase.class)
    public JAXBElement<UseCaseElementType> createHL7V2XConformanceProfileUseCasePreCondition(UseCaseElementType value) {
        return new JAXBElement<UseCaseElementType>(_HL7V2XConformanceProfileUseCasePreCondition_QNAME, UseCaseElementType.class, HL7V2XConformanceProfile.UseCase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseCaseElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DerivedEvent", scope = HL7V2XConformanceProfile.UseCase.class)
    public JAXBElement<UseCaseElementType> createHL7V2XConformanceProfileUseCaseDerivedEvent(UseCaseElementType value) {
        return new JAXBElement<UseCaseElementType>(_HL7V2XConformanceProfileUseCaseDerivedEvent_QNAME, UseCaseElementType.class, HL7V2XConformanceProfile.UseCase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseCaseElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EventFlow", scope = HL7V2XConformanceProfile.UseCase.class)
    public JAXBElement<UseCaseElementType> createHL7V2XConformanceProfileUseCaseEventFlow(UseCaseElementType value) {
        return new JAXBElement<UseCaseElementType>(_HL7V2XConformanceProfileUseCaseEventFlow_QNAME, UseCaseElementType.class, HL7V2XConformanceProfile.UseCase.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseCaseElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Actor", scope = HL7V2XConformanceProfile.UseCase.class)
    public JAXBElement<UseCaseElementType> createHL7V2XConformanceProfileUseCaseActor(UseCaseElementType value) {
        return new JAXBElement<UseCaseElementType>(_HL7V2XConformanceProfileUseCaseActor_QNAME, UseCaseElementType.class, HL7V2XConformanceProfile.UseCase.class, value);
    }

}
