//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.16 at 02:41:04 PM CEST 
//


package org.openehealth.ipf.gazelle.validation.core.stub;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SegmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}MessageElementsGroup"/>
 *         &lt;element name="Field" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{}LeafMessageElementsGroup"/>
 *                   &lt;element name="Component" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;group ref="{}LeafMessageElementsGroup"/>
 *                             &lt;element name="SubComponent" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;group ref="{}LeafMessageElementsGroup"/>
 *                                     &lt;attGroup ref="{}LeafElementAttributes"/>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attGroup ref="{}LeafElementAttributes"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{}LeafElementAttributes"/>
 *                 &lt;attGroup ref="{}RepeatableElementAttributes"/>
 *                 &lt;attribute name="ItemNo">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;pattern value="\d{5}|Z\d{4}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}RepeatableElementAttributes"/>
 *       &lt;attribute name="Name" use="required" type="{}SegmentNameType" />
 *       &lt;attribute ref="{}LongName"/>
 *       &lt;attribute ref="{}Usage use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegmentType", propOrder = {
    "impNote",
    "description",
    "reference",
    "predicate",
    "fields"
})
public class SegmentType {

    @XmlElement(name = "ImpNote")
    protected String impNote;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Reference")
    protected String reference;
    @XmlElement(name = "Predicate")
    protected String predicate;
    @XmlElement(name = "Field", required = true)
    protected List<SegmentType.Field> fields;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "LongName")
    protected String longName;
    @XmlAttribute(name = "Usage", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String usage;
    @XmlAttribute(name = "Min", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger min;
    @XmlAttribute(name = "Max", required = true)
    protected String max;

    /**
     * Gets the value of the impNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpNote() {
        return impNote;
    }

    /**
     * Sets the value of the impNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpNote(String value) {
        this.impNote = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the predicate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredicate() {
        return predicate;
    }

    /**
     * Sets the value of the predicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredicate(String value) {
        this.predicate = value;
    }

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SegmentType.Field }
     * 
     * 
     */
    public List<SegmentType.Field> getFields() {
        if (fields == null) {
            fields = new ArrayList<>();
        }
        return this.fields;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the longName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongName() {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongName(String value) {
        this.longName = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsage(String value) {
        this.usage = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMin(BigInteger value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMax(String value) {
        this.max = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{}LeafMessageElementsGroup"/>
     *         &lt;element name="Component" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;group ref="{}LeafMessageElementsGroup"/>
     *                   &lt;element name="SubComponent" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;group ref="{}LeafMessageElementsGroup"/>
     *                           &lt;attGroup ref="{}LeafElementAttributes"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attGroup ref="{}LeafElementAttributes"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{}LeafElementAttributes"/>
     *       &lt;attGroup ref="{}RepeatableElementAttributes"/>
     *       &lt;attribute name="ItemNo">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;pattern value="\d{5}|Z\d{4}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute ref="{http://www.openehealth.org/ipf}Nullable"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "impNote",
        "description",
        "reference",
        "predicate",
        "dataValues",
        "components"
    })
    public static class Field {

        @XmlElement(name = "ImpNote")
        protected String impNote;
        @XmlElement(name = "Description")
        protected String description;
        @XmlElement(name = "Reference")
        protected String reference;
        @XmlElement(name = "Predicate")
        protected String predicate;
        @XmlElement(name = "DataValues")
        protected List<SegmentType.Field.DataValues> dataValues;
        @XmlElement(name = "Component")
        protected List<SegmentType.Field.Component> components;
        @XmlAttribute(name = "ItemNo")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String itemNo;
        @XmlAttribute(name = "Name", required = true)
        protected String name;
        @XmlAttribute(name = "Usage", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String usage;
        @XmlAttribute(name = "Datatype", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String datatype;
        @XmlAttribute(name = "Length")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger length;
        @XmlAttribute(name = "Table")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String table;
        @XmlAttribute(name = "ConstantValue")
        protected String constantValue;
        @XmlAttribute(name = "Min", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger min;
        @XmlAttribute(name = "Max", required = true)
        protected String max;
        @XmlAttribute(name = "Nullable", namespace = "http://www.openehealth.org/ipf")
        protected boolean nullable;

        /**
         * Gets the value of the impNote property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImpNote() {
            return impNote;
        }

        /**
         * Sets the value of the impNote property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImpNote(String value) {
            this.impNote = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReference(String value) {
            this.reference = value;
        }

        /**
         * Gets the value of the predicate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPredicate() {
            return predicate;
        }

        /**
         * Sets the value of the predicate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPredicate(String value) {
            this.predicate = value;
        }

        /**
         * Gets the value of the dataValues property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataValues property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataValues().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SegmentType.Field.DataValues }
         * 
         * 
         */
        public List<SegmentType.Field.DataValues> getDataValues() {
            if (dataValues == null) {
                dataValues = new ArrayList<>();
            }
            return this.dataValues;
        }

        /**
         * Gets the value of the components property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the components property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComponents().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SegmentType.Field.Component }
         * 
         * 
         */
        public List<SegmentType.Field.Component> getComponents() {
            if (components == null) {
                components = new ArrayList<>();
            }
            return this.components;
        }

        /**
         * Gets the value of the itemNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemNo() {
            return itemNo;
        }

        /**
         * Sets the value of the itemNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemNo(String value) {
            this.itemNo = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the usage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsage() {
            return usage;
        }

        /**
         * Sets the value of the usage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsage(String value) {
            this.usage = value;
        }

        /**
         * Gets the value of the datatype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatype() {
            return datatype;
        }

        /**
         * Sets the value of the datatype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatype(String value) {
            this.datatype = value;
        }

        /**
         * Gets the value of the length property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLength(BigInteger value) {
            this.length = value;
        }

        /**
         * Gets the value of the table property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTable() {
            return table;
        }

        /**
         * Sets the value of the table property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTable(String value) {
            this.table = value;
        }

        /**
         * Gets the value of the constantValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstantValue() {
            return constantValue;
        }

        /**
         * Sets the value of the constantValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstantValue(String value) {
            this.constantValue = value;
        }

        /**
         * Gets the value of the min property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMin() {
            return min;
        }

        /**
         * Sets the value of the min property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMin(BigInteger value) {
            this.min = value;
        }

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMax(String value) {
            this.max = value;
        }

        /**
         * @return <code>true</code> if the HL7 NULL (a pair of double quotes <code>""</code>)
         * is a valid value for the whole field.
         * <p>
         * This attribute is an IPF extension.
         */
        public boolean isNullable() {
            return nullable;
        }

        /**
         * Defines whether the HL7 NULL (a pair of double quotes <code>""</code>)
         * shall be a valid value for the whole field.
         * <p>
         * This attribute is an IPF extension.
         * @param nullable
         *      if <code>true</code>, then the HL7 NULL (a pair of double quotes <code>""</code>)
         *      will be a valid value for the whole field.
         */
        public void setNullable(boolean nullable) {
            this.nullable = nullable;
        }

        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;group ref="{}LeafMessageElementsGroup"/>
         *         &lt;element name="SubComponent" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;group ref="{}LeafMessageElementsGroup"/>
         *                 &lt;attGroup ref="{}LeafElementAttributes"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attGroup ref="{}LeafElementAttributes"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "impNote",
            "description",
            "reference",
            "predicate",
            "dataValues",
            "subComponents"
        })
        public static class Component {

            @XmlElement(name = "ImpNote")
            protected String impNote;
            @XmlElement(name = "Description")
            protected String description;
            @XmlElement(name = "Reference")
            protected String reference;
            @XmlElement(name = "Predicate")
            protected String predicate;
            @XmlElement(name = "DataValues")
            protected List<SegmentType.Field.DataValues> dataValues;
            @XmlElement(name = "SubComponent")
            protected List<SegmentType.Field.Component.SubComponent> subComponents;
            @XmlAttribute(name = "Name", required = true)
            protected String name;
            @XmlAttribute(name = "Usage", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String usage;
            @XmlAttribute(name = "Datatype", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String datatype;
            @XmlAttribute(name = "Length")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger length;
            @XmlAttribute(name = "Table")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String table;
            @XmlAttribute(name = "ConstantValue")
            protected String constantValue;

            /**
             * Gets the value of the impNote property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImpNote() {
                return impNote;
            }

            /**
             * Sets the value of the impNote property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImpNote(String value) {
                this.impNote = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the reference property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReference() {
                return reference;
            }

            /**
             * Sets the value of the reference property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReference(String value) {
                this.reference = value;
            }

            /**
             * Gets the value of the predicate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPredicate() {
                return predicate;
            }

            /**
             * Sets the value of the predicate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPredicate(String value) {
                this.predicate = value;
            }

            /**
             * Gets the value of the dataValues property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dataValues property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDataValues().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SegmentType.Field.DataValues }
             * 
             * 
             */
            public List<SegmentType.Field.DataValues> getDataValues() {
                if (dataValues == null) {
                    dataValues = new ArrayList<>();
                }
                return this.dataValues;
            }

            /**
             * Gets the value of the subComponents property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the subComponents property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSubComponents().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SegmentType.Field.Component.SubComponent }
             * 
             * 
             */
            public List<SegmentType.Field.Component.SubComponent> getSubComponents() {
                if (subComponents == null) {
                    subComponents = new ArrayList<>();
                }
                return this.subComponents;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the usage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsage() {
                return usage;
            }

            /**
             * Sets the value of the usage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsage(String value) {
                this.usage = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                return datatype;
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

            /**
             * Gets the value of the length property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getLength() {
                return length;
            }

            /**
             * Sets the value of the length property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setLength(BigInteger value) {
                this.length = value;
            }

            /**
             * Gets the value of the table property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTable() {
                return table;
            }

            /**
             * Sets the value of the table property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTable(String value) {
                this.table = value;
            }

            /**
             * Gets the value of the constantValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConstantValue() {
                return constantValue;
            }

            /**
             * Sets the value of the constantValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConstantValue(String value) {
                this.constantValue = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;group ref="{}LeafMessageElementsGroup"/>
             *       &lt;attGroup ref="{}LeafElementAttributes"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "impNote",
                "description",
                "reference",
                "predicate",
                "dataValues"
            })
            public static class SubComponent {

                @XmlElement(name = "ImpNote")
                protected String impNote;
                @XmlElement(name = "Description")
                protected String description;
                @XmlElement(name = "Reference")
                protected String reference;
                @XmlElement(name = "Predicate")
                protected String predicate;
                @XmlElement(name = "DataValues")
                protected List<SegmentType.Field.DataValues> dataValues;
                @XmlAttribute(name = "Name", required = true)
                protected String name;
                @XmlAttribute(name = "Usage", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                protected String usage;
                @XmlAttribute(name = "Datatype", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                protected String datatype;
                @XmlAttribute(name = "Length")
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger length;
                @XmlAttribute(name = "Table")
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                protected String table;
                @XmlAttribute(name = "ConstantValue")
                protected String constantValue;

                /**
                 * Gets the value of the impNote property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getImpNote() {
                    return impNote;
                }

                /**
                 * Sets the value of the impNote property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setImpNote(String value) {
                    this.impNote = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the reference property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReference() {
                    return reference;
                }

                /**
                 * Sets the value of the reference property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReference(String value) {
                    this.reference = value;
                }

                /**
                 * Gets the value of the predicate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPredicate() {
                    return predicate;
                }

                /**
                 * Sets the value of the predicate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPredicate(String value) {
                    this.predicate = value;
                }

                /**
                 * Gets the value of the dataValues property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the dataValues property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDataValues().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link SegmentType.Field.DataValues }
                 * 
                 * 
                 */
                public List<SegmentType.Field.DataValues> getDataValues() {
                    if (dataValues == null) {
                        dataValues = new ArrayList<>();
                    }
                    return this.dataValues;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the usage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUsage() {
                    return usage;
                }

                /**
                 * Sets the value of the usage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUsage(String value) {
                    this.usage = value;
                }

                /**
                 * Gets the value of the datatype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDatatype() {
                    return datatype;
                }

                /**
                 * Sets the value of the datatype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatatype(String value) {
                    this.datatype = value;
                }

                /**
                 * Gets the value of the length property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getLength() {
                    return length;
                }

                /**
                 * Sets the value of the length property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setLength(BigInteger value) {
                    this.length = value;
                }

                /**
                 * Gets the value of the table property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTable() {
                    return table;
                }

                /**
                 * Sets the value of the table property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTable(String value) {
                    this.table = value;
                }

                /**
                 * Gets the value of the constantValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConstantValue() {
                    return constantValue;
                }

                /**
                 * Sets the value of the constantValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConstantValue(String value) {
                    this.constantValue = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="ExValue" type="{}NonEmptyStringType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DataValues {

            @XmlAttribute(name = "ExValue")
            protected String exValue;

            /**
             * Gets the value of the exValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExValue() {
                return exValue;
            }

            /**
             * Sets the value of the exValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExValue(String value) {
                this.exValue = value;
            }

        }

    }

}
